version: '3.3'
services:
  app:
    image: registry.heroku.com/fitlogapi/web
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      MICRONAUT_ENVIRONMENTS: docker
    depends_on:
      - database

  database:
    image: postgres:12-alpine # https://  devcenter.heroku.com/articles/heroku-postgresql#version-support
    environment:
      POSTGRES_USER: fitlog-api
      POSTGRES_PASSWORD: fitlog-api
      POSTGRES_DB: fitlog-api

  test:
    image: adoptopenjdk:11.0.5_10-jdk-hotspot
    command: /bin/sh -c './gradlew test'
    working_dir: /src
    volumes:
      - .:/src
    env_file:
      - .env
