datasources:
  default:
    url: jdbc:postgresql://database:5432/fitlog-api
    username: fitlog-api
    password: fitlog-api
    driverClassName: org.postgresql.Driver
    schema-generate: CREATE_DROP
